### ISSUE TITLE
SSL certificate integration with app

### ISSUE THREAD

**Issue by saptarshibasu** [saptarshibasu/hrms#1]
For now we will integrate private certificate with the app so that all the REST API calls and GUI URLs are accessed through HTTPS

**Comment by iSomdeb** [comment]
Initial HTTPS settings pushed with self-signed certificate. But, for now need to manually put the certificate file in the target folder from where jar would run.

**Comment by saptarshibasu** [comment]
moved the keystore to resources/ and changed the application.properties to read the keystore from classpath. With this change the manual dependency of moving the keystore to target is removed'
