### ISSUE TITLE
App deployment packaging using Maven

### ISSUE THREAD

**Issue by saptarshibasu** [saptarshibasu/hrms#3]

**Comment by saptarshibasu** [comment]
Please read [this](https://stackoverflow.com/a/26142103/1235935).

So. the final package will have the structure like:

hrms-->config-->keystore.p12
                        -->log4j2.xml
                        -->application.properties
        -->dist     -->hrms.jar
        start_hrms.sh
        start_hrms.bat

**Comment by chandab0** [comment]
Ref link: https://dzone.com/articles/packaging-springboot-application-with-external-dep

**Comment by saptarshibasu** [comment]
Ok. Yes this is a good link. This is exactly what we need. Please follow this.

**Comment by chandab0** [comment]
Packaging part is ready.

Build the distribution packge using: 'mvn clean install'

Inside hrms\hua-server\target directory hrms-distribution.zip and hrms-distribution.tar will be created.

Ship hrms-distribution.zip to desired location.

Extract hrms-distribution.zip which will give you directory structure as tabulated below:

hrms --> config --> Application-prod.properties

hrms --> config --> keystore.p12

hrms --> config --> log4j2.xml

hrms --> lib --> hrms.jar

hrms --> log

hrms --> start_hrms.bat

hrms --> start_hrms.sh

Execute start_hrms.bat to start the application by passing argument (e.g prod). If no argument is passed, the default will be taken as prod. './start_hrms.bat prod'
